import { describe, expect, it } from 'vitest';

import { createRouteRegistry } from '../../src/presentation/http/route-registry.factory.js';
import { isPublicRoute } from '../../src/presentation/http/route-registry.types.js';
import { createTestApp } from '../support/test-app.util.js';

/**
 * Every route reachable without authentication, written out in full.
 *
 * ## Why a list and not a rule
 *
 * The neighbouring check in `openapi.test.ts` («gives every product operation a permission or a
 * stated reason for being public») asks whether a public route *explained itself*, and a sentence
 * is cheap to write. It passes for a route that should never have been public at all, as long as
 * somebody typed a reason next to it. What it cannot do is make the **set** visible: a route added
 * to it changes no assertion, and the diff that opens the whole product to anonymous callers looks
 * in review exactly like the diff that adds an authenticated one.
 *
 * So the set itself is the assertion. Adding, removing or renaming a public route fails this test
 * and the fix is to edit the list below — which puts the change in the diff, under the eyes of
 * whoever reviews it, next to the reason it was made. That is the whole mechanism STORY-013-03
 * acceptance 12 asks for: «список публичных маршрутов снапшотится и его изменение требует ревью».
 *
 * ## Why it is written here rather than taken with `toMatchSnapshot`
 *
 * An external snapshot file is regenerated by `-u`, and a run with `-u` is how an unreviewed public
 * route gets blessed by a keystroke while the reviewer sees only «snapshot updated». Written
 * inline, the list is source: it cannot be refreshed automatically, and changing it is an edit
 * somebody makes on purpose.
 *
 * A route belongs on this list only if it must answer somebody who has no session **yet** — signing
 * in, recovering a password, accepting an invitation, the operational probes — never merely
 * because a permission was inconvenient to pick.
 */
const EXPECTED_PUBLIC_ROUTES: readonly string[] = [
  // Operational probes. No tenant data, and an orchestrator has no session to present.
  'GET /health',
  'GET /ready',
  // What this installation is and which optional subsystems it runs — read by the client before
  // anybody has signed in, to know which screens exist at all.
  'GET /api/v1/meta',
  // The four pre-session credential routes: there is no session to authorise them with, which is
  // the point of each. All four are bounded by `auth_attempt` or its siblings rather than by a
  // permission.
  'POST /api/v1/auth/register',
  'POST /api/v1/auth/login',
  'POST /api/v1/auth/forgot-password',
  'POST /api/v1/auth/reset-password',
  // Accepting an invitation creates the account that would otherwise hold the session.
  'POST /api/v1/invitations/accept',
  // Client-side crash reports: the browser that failed may be the one that could not sign in.
  'POST /api/v1/telemetry/client-error',
];

const sorted = (routes: readonly string[]): string[] =>
  [...routes].sort((left, right) => left.localeCompare(right));

const publicRoutes = (): string[] =>
  sorted(
    createRouteRegistry(createTestApp().container.http)
      .filter(isPublicRoute)
      .map((route) => `${route.method.toUpperCase()} ${route.path}`),
  );

describe('the set of routes reachable without authentication', () => {
  /**
   * Both sides are sorted before comparing, so the list above can stay grouped by *why* a route is
   * public — probes, then the pre-session credential routes — instead of by byte order. The reason
   * a route is exempt is what a reviewer needs next to it; alphabetical order would scatter the
   * four credential routes across the list and put `forgot-password` next to `/health`.
   */
  it('is exactly the reviewed list', () => {
    expect(publicRoutes()).toEqual(sorted(EXPECTED_PUBLIC_ROUTES));
  });

  /**
   * The positive control for the assertion above.
   *
   * Without it an empty registry — a `createTestApp` that failed to mount anything, a filter that
   * stopped matching — satisfies «equals the expected list» the moment the expected list is also
   * empty, and the suite reports that the public surface is under review while measuring nothing.
   */
  it('is not empty, so the comparison above is measuring something', () => {
    expect(publicRoutes().length).toBeGreaterThan(0);
  });
});
