/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as InviteTokenRouteImport } from './routes/invite.$token';
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token';
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles';
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin/members/index';
import { Route as AuthenticatedAdminMembersUserIdRouteImport } from './routes/_authenticated/admin/members/$userId';
import { Route as AuthenticatedAdminMembersInviteRouteImport } from './routes/_authenticated/admin/members/invite';
import { Route as AuthenticatedAdminTeamsIndexRouteImport } from './routes/_authenticated/admin/teams/index';
import { Route as AuthenticatedAdminTeamsTeamIdRouteImport } from './routes/_authenticated/admin/teams/$teamId';

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/admin/members/',
    path: '/admin/members/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminMembersUserIdRoute =
  AuthenticatedAdminMembersUserIdRouteImport.update({
    id: '/admin/members/$userId',
    path: '/admin/members/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminMembersInviteRoute =
  AuthenticatedAdminMembersInviteRouteImport.update({
    id: '/admin/members/invite',
    path: '/admin/members/invite',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminTeamsIndexRoute =
  AuthenticatedAdminTeamsIndexRouteImport.update({
    id: '/admin/teams/',
    path: '/admin/teams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminTeamsTeamIdRoute =
  AuthenticatedAdminTeamsTeamIdRouteImport.update({
    id: '/admin/teams/$teamId',
    path: '/admin/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/$': typeof AuthenticatedSplatRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/reset-password/$token': typeof ResetPasswordTokenRoute;
  '/admin/roles': typeof AuthenticatedAdminRolesRoute;
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute;
  '/admin/members/invite': typeof AuthenticatedAdminMembersInviteRoute;
  '/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute;
  '/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute;
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/$': typeof AuthenticatedSplatRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/reset-password/$token': typeof ResetPasswordTokenRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/admin/roles': typeof AuthenticatedAdminRolesRoute;
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute;
  '/admin/members/invite': typeof AuthenticatedAdminMembersInviteRoute;
  '/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute;
  '/admin/teams': typeof AuthenticatedAdminTeamsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/_authenticated/$': typeof AuthenticatedSplatRoute;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/reset-password/$token': typeof ResetPasswordTokenRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute;
  '/_authenticated/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute;
  '/_authenticated/admin/members/invite': typeof AuthenticatedAdminMembersInviteRoute;
  '/_authenticated/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute;
  '/_authenticated/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/$'
    | '/dashboard'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/admin/roles'
    | '/admin/members/$userId'
    | '/admin/members/invite'
    | '/admin/teams/$teamId'
    | '/admin/members/'
    | '/admin/teams/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/forgot-password'
    | '/login'
    | '/$'
    | '/dashboard'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/'
    | '/admin/roles'
    | '/admin/members/$userId'
    | '/admin/members/invite'
    | '/admin/teams/$teamId'
    | '/admin/members'
    | '/admin/teams';
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/_authenticated/$'
    | '/_authenticated/dashboard'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/_authenticated/'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/members/$userId'
    | '/_authenticated/admin/members/invite'
    | '/_authenticated/admin/teams/$teamId'
    | '/_authenticated/admin/members/'
    | '/_authenticated/admin/teams/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/$': {
      id: '/_authenticated/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof AuthenticatedSplatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/invite/$token': {
      id: '/invite/$token';
      path: '/invite/$token';
      fullPath: '/invite/$token';
      preLoaderRoute: typeof InviteTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password/$token': {
      id: '/reset-password/$token';
      path: '/reset-password/$token';
      fullPath: '/reset-password/$token';
      preLoaderRoute: typeof ResetPasswordTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles';
      path: '/admin/roles';
      fullPath: '/admin/roles';
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/';
      path: '/admin/members';
      fullPath: '/admin/members/';
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/$userId': {
      id: '/_authenticated/admin/members/$userId';
      path: '/admin/members/$userId';
      fullPath: '/admin/members/$userId';
      preLoaderRoute: typeof AuthenticatedAdminMembersUserIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/invite': {
      id: '/_authenticated/admin/members/invite';
      path: '/admin/members/invite';
      fullPath: '/admin/members/invite';
      preLoaderRoute: typeof AuthenticatedAdminMembersInviteRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/teams/': {
      id: '/_authenticated/admin/teams/';
      path: '/admin/teams';
      fullPath: '/admin/teams/';
      preLoaderRoute: typeof AuthenticatedAdminTeamsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/teams/$teamId': {
      id: '/_authenticated/admin/teams/$teamId';
      path: '/admin/teams/$teamId';
      fullPath: '/admin/teams/$teamId';
      preLoaderRoute: typeof AuthenticatedAdminTeamsTeamIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute;
  AuthenticatedAdminMembersUserIdRoute: typeof AuthenticatedAdminMembersUserIdRoute;
  AuthenticatedAdminMembersInviteRoute: typeof AuthenticatedAdminMembersInviteRoute;
  AuthenticatedAdminTeamsTeamIdRoute: typeof AuthenticatedAdminTeamsTeamIdRoute;
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute;
  AuthenticatedAdminTeamsIndexRoute: typeof AuthenticatedAdminTeamsIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminMembersUserIdRoute: AuthenticatedAdminMembersUserIdRoute,
  AuthenticatedAdminMembersInviteRoute: AuthenticatedAdminMembersInviteRoute,
  AuthenticatedAdminTeamsTeamIdRoute: AuthenticatedAdminTeamsTeamIdRoute,
  AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  AuthenticatedAdminTeamsIndexRoute: AuthenticatedAdminTeamsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
