/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as MfaEnrolmentRouteImport } from './routes/mfa-enrolment';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as InviteTokenRouteImport } from './routes/invite.$token';
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token';
import { Route as AuthenticatedAdminOrganizationRouteImport } from './routes/_authenticated/admin/organization';
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles';
import { Route as AuthenticatedProjectsProjectIdRouteRouteImport } from './routes/_authenticated/projects/$projectId/route';
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new';
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security';
import { Route as AuthenticatedAdminMembersIndexRouteImport } from './routes/_authenticated/admin/members/index';
import { Route as AuthenticatedAdminMembersUserIdRouteImport } from './routes/_authenticated/admin/members/$userId';
import { Route as AuthenticatedAdminMembersInvitationsRouteImport } from './routes/_authenticated/admin/members/invitations';
import { Route as AuthenticatedAdminMembersInviteRouteImport } from './routes/_authenticated/admin/members/invite';
import { Route as AuthenticatedAdminTeamsIndexRouteImport } from './routes/_authenticated/admin/teams/index';
import { Route as AuthenticatedAdminTeamsTeamIdRouteImport } from './routes/_authenticated/admin/teams/$teamId';
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index';
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects/$projectId/members';
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/projects/$projectId/settings';

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const MfaEnrolmentRoute = MfaEnrolmentRouteImport.update({
  id: '/mfa-enrolment',
  path: '/mfa-enrolment',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedAdminOrganizationRoute =
  AuthenticatedAdminOrganizationRouteImport.update({
    id: '/admin/organization',
    path: '/admin/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedProjectsProjectIdRouteRoute =
  AuthenticatedProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminMembersIndexRoute =
  AuthenticatedAdminMembersIndexRouteImport.update({
    id: '/admin/members/',
    path: '/admin/members/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminMembersUserIdRoute =
  AuthenticatedAdminMembersUserIdRouteImport.update({
    id: '/admin/members/$userId',
    path: '/admin/members/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminMembersInvitationsRoute =
  AuthenticatedAdminMembersInvitationsRouteImport.update({
    id: '/admin/members/invitations',
    path: '/admin/members/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminMembersInviteRoute =
  AuthenticatedAdminMembersInviteRouteImport.update({
    id: '/admin/members/invite',
    path: '/admin/members/invite',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminTeamsIndexRoute =
  AuthenticatedAdminTeamsIndexRouteImport.update({
    id: '/admin/teams/',
    path: '/admin/teams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminTeamsTeamIdRoute =
  AuthenticatedAdminTeamsTeamIdRouteImport.update({
    id: '/admin/teams/$teamId',
    path: '/admin/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any);
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any);
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/mfa-enrolment': typeof MfaEnrolmentRoute;
  '/register': typeof RegisterRoute;
  '/$': typeof AuthenticatedSplatRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/reset-password/$token': typeof ResetPasswordTokenRoute;
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren;
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute;
  '/admin/roles': typeof AuthenticatedAdminRolesRoute;
  '/projects/new': typeof AuthenticatedProjectsNewRoute;
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute;
  '/admin/members/invitations': typeof AuthenticatedAdminMembersInvitationsRoute;
  '/admin/members/invite': typeof AuthenticatedAdminMembersInviteRoute;
  '/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute;
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute;
  '/admin/members/': typeof AuthenticatedAdminMembersIndexRoute;
  '/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute;
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute;
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/mfa-enrolment': typeof MfaEnrolmentRoute;
  '/register': typeof RegisterRoute;
  '/$': typeof AuthenticatedSplatRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/reset-password/$token': typeof ResetPasswordTokenRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute;
  '/admin/roles': typeof AuthenticatedAdminRolesRoute;
  '/projects/new': typeof AuthenticatedProjectsNewRoute;
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute;
  '/admin/members/invitations': typeof AuthenticatedAdminMembersInvitationsRoute;
  '/admin/members/invite': typeof AuthenticatedAdminMembersInviteRoute;
  '/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute;
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute;
  '/admin/members': typeof AuthenticatedAdminMembersIndexRoute;
  '/admin/teams': typeof AuthenticatedAdminTeamsIndexRoute;
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/mfa-enrolment': typeof MfaEnrolmentRoute;
  '/register': typeof RegisterRoute;
  '/_authenticated/$': typeof AuthenticatedSplatRoute;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/invite/$token': typeof InviteTokenRoute;
  '/reset-password/$token': typeof ResetPasswordTokenRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren;
  '/_authenticated/admin/organization': typeof AuthenticatedAdminOrganizationRoute;
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute;
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute;
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/_authenticated/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute;
  '/_authenticated/admin/members/invitations': typeof AuthenticatedAdminMembersInvitationsRoute;
  '/_authenticated/admin/members/invite': typeof AuthenticatedAdminMembersInviteRoute;
  '/_authenticated/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute;
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute;
  '/_authenticated/admin/members/': typeof AuthenticatedAdminMembersIndexRoute;
  '/_authenticated/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute;
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mfa-enrolment'
    | '/register'
    | '/$'
    | '/dashboard'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/projects/$projectId'
    | '/admin/organization'
    | '/admin/roles'
    | '/projects/new'
    | '/settings/security'
    | '/admin/members/$userId'
    | '/admin/members/invitations'
    | '/admin/members/invite'
    | '/admin/teams/$teamId'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/admin/members/'
    | '/admin/teams/'
    | '/projects/$projectId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/forgot-password'
    | '/login'
    | '/mfa-enrolment'
    | '/register'
    | '/$'
    | '/dashboard'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/'
    | '/admin/organization'
    | '/admin/roles'
    | '/projects/new'
    | '/settings/security'
    | '/admin/members/$userId'
    | '/admin/members/invitations'
    | '/admin/members/invite'
    | '/admin/teams/$teamId'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/admin/members'
    | '/admin/teams'
    | '/projects/$projectId';
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/mfa-enrolment'
    | '/register'
    | '/_authenticated/$'
    | '/_authenticated/dashboard'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/_authenticated/'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/admin/organization'
    | '/_authenticated/admin/roles'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/security'
    | '/_authenticated/admin/members/$userId'
    | '/_authenticated/admin/members/invitations'
    | '/_authenticated/admin/members/invite'
    | '/_authenticated/admin/teams/$teamId'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/admin/members/'
    | '/_authenticated/admin/teams/'
    | '/_authenticated/projects/$projectId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  MfaEnrolmentRoute: typeof MfaEnrolmentRoute;
  RegisterRoute: typeof RegisterRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/mfa-enrolment': {
      id: '/mfa-enrolment';
      path: '/mfa-enrolment';
      fullPath: '/mfa-enrolment';
      preLoaderRoute: typeof MfaEnrolmentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/$': {
      id: '/_authenticated/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof AuthenticatedSplatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/invite/$token': {
      id: '/invite/$token';
      path: '/invite/$token';
      fullPath: '/invite/$token';
      preLoaderRoute: typeof InviteTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password/$token': {
      id: '/reset-password/$token';
      path: '/reset-password/$token';
      fullPath: '/reset-password/$token';
      preLoaderRoute: typeof ResetPasswordTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/admin/organization': {
      id: '/_authenticated/admin/organization';
      path: '/admin/organization';
      fullPath: '/admin/organization';
      preLoaderRoute: typeof AuthenticatedAdminOrganizationRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles';
      path: '/admin/roles';
      fullPath: '/admin/roles';
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId';
      path: '/projects/$projectId';
      fullPath: '/projects/$projectId';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new';
      path: '/projects/new';
      fullPath: '/projects/new';
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security';
      path: '/settings/security';
      fullPath: '/settings/security';
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/': {
      id: '/_authenticated/admin/members/';
      path: '/admin/members';
      fullPath: '/admin/members/';
      preLoaderRoute: typeof AuthenticatedAdminMembersIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/$userId': {
      id: '/_authenticated/admin/members/$userId';
      path: '/admin/members/$userId';
      fullPath: '/admin/members/$userId';
      preLoaderRoute: typeof AuthenticatedAdminMembersUserIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/invitations': {
      id: '/_authenticated/admin/members/invitations';
      path: '/admin/members/invitations';
      fullPath: '/admin/members/invitations';
      preLoaderRoute: typeof AuthenticatedAdminMembersInvitationsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/members/invite': {
      id: '/_authenticated/admin/members/invite';
      path: '/admin/members/invite';
      fullPath: '/admin/members/invite';
      preLoaderRoute: typeof AuthenticatedAdminMembersInviteRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/teams/': {
      id: '/_authenticated/admin/teams/';
      path: '/admin/teams';
      fullPath: '/admin/teams/';
      preLoaderRoute: typeof AuthenticatedAdminTeamsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/teams/$teamId': {
      id: '/_authenticated/admin/teams/$teamId';
      path: '/admin/teams/$teamId';
      fullPath: '/admin/teams/$teamId';
      preLoaderRoute: typeof AuthenticatedAdminTeamsTeamIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/';
      path: '/';
      fullPath: '/projects/$projectId/';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute;
    };
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members';
      path: '/members';
      fullPath: '/projects/$projectId/members';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute;
    };
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings';
      path: '/settings';
      fullPath: '/projects/$projectId/settings';
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport;
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute;
    };
  }
}

interface AuthenticatedProjectsProjectIdRouteRouteChildren {
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute;
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute;
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute;
}

const AuthenticatedProjectsProjectIdRouteRouteChildren: AuthenticatedProjectsProjectIdRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdMembersRoute:
      AuthenticatedProjectsProjectIdMembersRoute,
    AuthenticatedProjectsProjectIdSettingsRoute:
      AuthenticatedProjectsProjectIdSettingsRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  };

const AuthenticatedProjectsProjectIdRouteRouteWithChildren =
  AuthenticatedProjectsProjectIdRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedProjectsProjectIdRouteRoute: typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren;
  AuthenticatedAdminOrganizationRoute: typeof AuthenticatedAdminOrganizationRoute;
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute;
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute;
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute;
  AuthenticatedAdminMembersUserIdRoute: typeof AuthenticatedAdminMembersUserIdRoute;
  AuthenticatedAdminMembersInvitationsRoute: typeof AuthenticatedAdminMembersInvitationsRoute;
  AuthenticatedAdminMembersInviteRoute: typeof AuthenticatedAdminMembersInviteRoute;
  AuthenticatedAdminTeamsTeamIdRoute: typeof AuthenticatedAdminTeamsTeamIdRoute;
  AuthenticatedAdminMembersIndexRoute: typeof AuthenticatedAdminMembersIndexRoute;
  AuthenticatedAdminTeamsIndexRoute: typeof AuthenticatedAdminTeamsIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRouteRoute:
    AuthenticatedProjectsProjectIdRouteRouteWithChildren,
  AuthenticatedAdminOrganizationRoute: AuthenticatedAdminOrganizationRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedAdminMembersUserIdRoute: AuthenticatedAdminMembersUserIdRoute,
  AuthenticatedAdminMembersInvitationsRoute:
    AuthenticatedAdminMembersInvitationsRoute,
  AuthenticatedAdminMembersInviteRoute: AuthenticatedAdminMembersInviteRoute,
  AuthenticatedAdminTeamsTeamIdRoute: AuthenticatedAdminTeamsTeamIdRoute,
  AuthenticatedAdminMembersIndexRoute: AuthenticatedAdminMembersIndexRoute,
  AuthenticatedAdminTeamsIndexRoute: AuthenticatedAdminTeamsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MfaEnrolmentRoute: MfaEnrolmentRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
