/* eslint-disable bad-crm/require-role-suffix --
 * `.catalog` is not in the closed suffix dictionary of rules/naming-and-structure.mdc, but this
 * exact path is mandated by a higher source of truth: invariant 2 in CLAUDE.md and
 * docs/security/permission-model.md §1 both name
 * `packages/shared/src/permissions/permissions.catalog.ts` as *the* permission catalog, and the
 * `permission-matrix-auditor` agent looks for it there. Renaming the file to satisfy the linter
 * would break the normative reference; adding `.catalog` to the dictionary is a change to
 * rules/naming-and-structure.mdc and belongs to the person who owns that rule file.
 */
import type { AccessLevel } from './access-level.enums.js';

/**
 * Layer 1 of the permission model: the closed catalog of permission keys.
 *
 * Transcribed from `docs/security/permission-model.md` §3, which stays the source of truth for the
 * *list*: keys are added to the document first and copied here, never invented at a call site. The
 * two are held together by `test/permissions/catalog-matches-model.test.ts`, which parses the tables
 * of that document and fails on any key, resource, action, domain, ACL level or `dangerous` flag
 * that differs — including the totals the document states in prose. Without that gate the copy would
 * be a promise; with it, the document and the type cannot drift apart in silence.
 *
 * Rules that apply to every key here (`docs/security/permission-model.md` §1):
 *
 * 1. A permission exists only if some use-case checks it.
 * 2. Keys are never reused: a removed key does not come back with a different meaning, or historic
 *    `RolePermission` rows and `AuditLog` entries start meaning something else.
 * 3. `requiredLevel` lives in code only — it is a property of the logic, not of the data, and it
 *    changes together with the use-case.
 */
export const PERMISSIONS = [
  'organization:read',
  'organization:update',
  'organization:manage_branding',
  'organization:manage_locale',
  'organization:manage_security_policy',
  'organization:manage_signing_key',
  'organization:manage_storage',
  'organization:view_usage',
  'organization:export_data',
  'organization:transfer_ownership',
  'organization:delete',
  'team:read',
  'team:create',
  'team:update',
  'team:delete',
  'team:manage_members',
  'mail:read_own',
  'mail:manage_domain',
  'mail:create_account',
  'mail:update_account',
  'mail:delete_account',
  'mail:manage_alias',
  'mail:view_any_account',
  'user:read',
  'user:invite',
  'user:update',
  'user:suspend',
  'user:reactivate',
  'user:delete',
  'user:reset_password',
  'user:reset_mfa',
  'user:force_logout',
  'user:read_sessions',
  'user:impersonate',
  'invitation:read',
  'invitation:create',
  'invitation:resend',
  'invitation:revoke',
  'employee:read',
  'employee:update',
  'employee:view_org_chart',
  'employee:view_capacity',
  'employee:manage_employment',
  'employee:view_personal_data',
  'employee:view_cost_rate',
  'employee:manage_cost_rate',
  'employee:view_drilldown',
  'role:read',
  'role:create',
  'role:update',
  'role:delete',
  'role:assign',
  'role:revoke',
  'permission:read',
  'permission:override_read',
  'permission:override',
  'permission:explain',
  'acl:read',
  'acl:grant',
  'acl:revoke',
  'project:read',
  'project:create',
  'project:update',
  'project:archive',
  'project:delete',
  'project:manage_members',
  'project:manage_settings',
  'project:manage_visibility',
  'project:manage_labels',
  'project:view_budget',
  'project:manage_budget',
  'project:view_financials',
  'board:read',
  'board:create',
  'board:update',
  'board:delete',
  'board:manage_columns',
  'board:override_wip_limit',
  'task:read',
  'task:create',
  'task:update',
  'task:move',
  'task:assign',
  'task:estimate',
  'task:link',
  'task:manage_labels',
  'task:manage_sprint',
  'task:watch',
  'task:delete',
  'task:restore',
  'task:bulk_edit',
  'task:export',
  'sprint:read',
  'sprint:create',
  'sprint:update',
  'sprint:start',
  'sprint:complete',
  'sprint:delete',
  'comment:read',
  'comment:create',
  'comment:update_own',
  'comment:update_any',
  'comment:delete_own',
  'comment:delete_any',
  'comment:resolve',
  'doc:read',
  'doc:create',
  'doc:update',
  'doc:move',
  'doc:delete',
  'doc:publish',
  'doc:view_history',
  'doc:restore_version',
  'doc:export',
  'doc:import',
  'doc:share',
  'doc:manage_acl',
  'kb_space:read',
  'kb_space:create',
  'kb_space:update',
  'kb_space:delete',
  'kb_space:manage_acl',
  'kb_space:sync_git',
  'kb_space:import',
  'kb_space:export',
  'kb_note:read',
  'kb_note:create',
  'kb_note:update',
  'kb_note:delete',
  'kb_note:manage_tags',
  'kb_note:view_graph',
  'file:read',
  'file:download',
  'file:upload',
  'file:update',
  'file:delete',
  'file:restore',
  'file:manage_versions',
  'file:manage_folders',
  'file:manage_acl',
  'file:view_quarantined',
  'file:download_quarantined',
  'file:manage_retention',
  'file:view_quota',
  'vault:read',
  'vault:create',
  'vault:update',
  'vault:delete',
  'vault:view_members',
  'vault:share',
  'vault:revoke_access',
  'vault:rotate_keys',
  'vault:rotate_payload',
  'vault:view_access_log',
  'vault:manage_org_escrow',
  'vault:use_org_escrow',
  'vault_item:read',
  'vault_item:create',
  'vault_item:update',
  'vault_item:delete',
  'vault_item:decrypt',
  'vault_item:export',
  'vault_item:view_history',
  'secure_link:read',
  'secure_link:read_any',
  'secure_link:create',
  'secure_link:attach_resource',
  'secure_link:revoke',
  'secure_link:view_access_log',
  'secure_link:manage_policy',
  'time:track',
  'time:manage_activities',
  'time:reverse_entry',
  'time:read_own',
  'time:read_team',
  'time:read_all',
  'time:create_own',
  'time:update_own',
  'time:delete_own',
  'time:update_any',
  'time:delete_any',
  'time:override',
  'time:manage_policy',
  'time:view_cost',
  'time:view_bill_rate',
  'time:manage_bill_rate',
  'time:export',
  'timesheet:read_own',
  'timesheet:read_team',
  'timesheet:read_all',
  'timesheet:submit',
  'timesheet:approve',
  'timesheet:reject',
  'timesheet:reopen',
  'timesheet:unlock_period',
  'channel:read',
  'channel:read_any',
  'channel:create',
  'channel:update',
  'channel:join_public',
  'channel:manage_members',
  'channel:archive',
  'channel:delete',
  'channel:export',
  'message:create',
  'message:update_own',
  'message:delete_own',
  'message:delete_any',
  'message:pin',
  'message:mention_channel',
  'message:react',
  'message:search',
  'dashboard:read',
  'dashboard:create',
  'dashboard:update',
  'dashboard:delete',
  'dashboard:share',
  'report:read',
  'report:read_team',
  'report:read_org',
  'report:read_people',
  'report:view_cost',
  'report:view_margin',
  'report:export',
  'integration:read',
  'integration:connect',
  'integration:disconnect',
  'integration:manage_secrets',
  'repo_link:read',
  'repo_link:create',
  'repo_link:delete',
  'ci:read',
  'ci:rerun',
  'ci:cancel',
  'deployment:read',
  'deployment:trigger',
  'webhook:view_deliveries',
  'webhook:replay',
  'ai:use',
  'ai:use_project_context',
  'ai:read_own_threads',
  'ai:read_any_thread',
  'ai:delete_thread',
  'ai:run_tools',
  'ai:view_usage',
  'ai:manage_budget',
  'ai:manage_tool_policy',
  'ai:configure_providers',
  'ai:reindex_embeddings',
  'delivery:access',
  'client:read',
  'client:create',
  'client:update',
  'client:delete',
  'client:manage_contacts',
  'contract:read',
  'contract:create',
  'contract:update',
  'contract:change_status',
  'contract:terminate',
  'contract:view_rates',
  'contract:manage_rates',
  'contract:view_nda',
  'invoice:read',
  'invoice:create',
  'invoice:update',
  'invoice:issue',
  'invoice:send',
  'invoice:void',
  'invoice:export',
  'payment:read',
  'payment:record',
  'payment:delete',
  'milestone:read',
  'milestone:create',
  'milestone:update',
  'milestone:accept',
  'call:read',
  'call:create',
  'call:update',
  'call:delete',
  'call:manage_participants',
  'call:view_recording',
  'call:manage_summary',
  'call:export',
  'action_item:read',
  'action_item:create',
  'action_item:update',
  'action_item:complete',
  'risk:read',
  'risk:create',
  'risk:update',
  'risk:close',
  'stakeholder:read',
  'stakeholder:manage',
  'audit:read',
  'audit:read_security',
  'audit:export',
  'audit:manage_retention',
  'settings:read',
  'settings:update',
  'settings:manage_email',
  'settings:manage_storage_backend',
  'settings:manage_backup',
  'settings:run_backup',
  'settings:restore_backup',
  'settings:view_system_health',
  'settings:manage_feature_flags',
  'api_token:read_own',
  'api_token:create_own',
  'api_token:revoke_own',
  'api_token:read_any',
  'api_token:revoke_any',
  'mcp:connect',
  'mcp:use_write_tools',
  'mcp:manage_clients',
  'mcp:manage_tool_policy',
  'mcp:read_any_session',
  'mcp:revoke_any_session',
  'notification:read_own',
  'notification:manage_preferences_own',
  'notification:manage_templates',
  'onboarding:read',
  'onboarding:manage',
  'material:read',
  'material:create',
  'material:update',
  'material:delete',
  'search:reindex',
  'job:read',
  'job:retry',
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

/** Bounded contexts the keys are grouped by (docs/architecture/overview.md). */
export const PERMISSION_DOMAINS = [
  'organization',
  'iam',
  'project',
  'task',
  'knowledge',
  'file',
  'vault',
  'secure-link',
  'time',
  'communication',
  'analytics',
  'integration',
  'ai',
  'delivery',
  'platform',
] as const;

export type PermissionDomain = (typeof PERMISSION_DOMAINS)[number];

export interface PermissionMeta {
  /** Part of the key before the colon. */
  readonly resource: string;
  /** Part of the key after the colon. */
  readonly action: string;
  readonly domain: PermissionDomain;
  /** `null` — the permission is organization-scoped and needs no resource ACL. */
  readonly requiredLevel: AccessLevel | null;
  /** Needs confirmation in the UI, a louder audit record and attention at review. */
  readonly dangerous: boolean;
  /** An i18n key, not a ready-made sentence: the description is translated (rules/i18n.mdc). */
  readonly descriptionKey: string;
  /** Set when a key is retired. The string stays for the sake of readable historic dumps. */
  readonly deprecated?: { readonly since: string; readonly replacedBy?: PermissionKey };
}

export const PERMISSION_META: Readonly<Record<PermissionKey, PermissionMeta>> = {
  'organization:read': {
    resource: 'organization',
    action: 'read',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.organization.read',
  },
  'organization:update': {
    resource: 'organization',
    action: 'update',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.organization.update',
  },
  'organization:manage_branding': {
    resource: 'organization',
    action: 'manage_branding',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.organization.manage_branding',
  },
  'organization:manage_locale': {
    resource: 'organization',
    action: 'manage_locale',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.organization.manage_locale',
  },
  'organization:manage_security_policy': {
    resource: 'organization',
    action: 'manage_security_policy',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.organization.manage_security_policy',
  },
  'organization:manage_signing_key': {
    resource: 'organization',
    action: 'manage_signing_key',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.organization.manage_signing_key',
  },
  'organization:manage_storage': {
    resource: 'organization',
    action: 'manage_storage',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.organization.manage_storage',
  },
  'organization:view_usage': {
    resource: 'organization',
    action: 'view_usage',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.organization.view_usage',
  },
  'organization:export_data': {
    resource: 'organization',
    action: 'export_data',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.organization.export_data',
  },
  'organization:transfer_ownership': {
    resource: 'organization',
    action: 'transfer_ownership',
    domain: 'organization',
    // `null`, like `team:*` below: `MANAGER` here used to name a resource-level check nothing
    // reads. There is no `ResourceAcl` for any domain yet (STORY-011-06 is blocked on EPIC-014, and
    // `require-permission.middleware.ts` only ever calls `authorizeCapability`, never
    // `authorizeResource`/`authorizeWith`, for this key) — so the field was a promise, not a check.
    // The actual decision belongs to `TransferOwnershipUseCase`, which reads
    // `organizations.owner_id` inside its own transaction and refuses a caller who holds this
    // capability without holding that row (`domain/iam/access/ownership-transfer.policy.ts`,
    // deny reason `not_the_owner`) — a check this catalog cannot express, because it depends on data
    // no ACL level carries.
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.organization.transfer_ownership',
  },
  'organization:delete': {
    resource: 'organization',
    action: 'delete',
    domain: 'organization',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.organization.delete',
  },
  'team:read': {
    resource: 'team',
    action: 'read',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.team.read',
  },
  'team:create': {
    resource: 'team',
    action: 'create',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.team.create',
  },
  'team:update': {
    resource: 'team',
    action: 'update',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.team.update',
  },
  'team:delete': {
    resource: 'team',
    action: 'delete',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.team.delete',
  },
  'team:manage_members': {
    resource: 'team',
    action: 'manage_members',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.team.manage_members',
  },
  'mail:read_own': {
    resource: 'mail',
    action: 'read_own',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.mail.read_own',
  },
  'mail:manage_domain': {
    resource: 'mail',
    action: 'manage_domain',
    domain: 'organization',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mail.manage_domain',
  },
  'mail:create_account': {
    resource: 'mail',
    action: 'create_account',
    domain: 'organization',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mail.create_account',
  },
  'mail:update_account': {
    resource: 'mail',
    action: 'update_account',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.mail.update_account',
  },
  'mail:delete_account': {
    resource: 'mail',
    action: 'delete_account',
    domain: 'organization',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mail.delete_account',
  },
  'mail:manage_alias': {
    resource: 'mail',
    action: 'manage_alias',
    domain: 'organization',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.mail.manage_alias',
  },
  'mail:view_any_account': {
    resource: 'mail',
    action: 'view_any_account',
    domain: 'organization',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mail.view_any_account',
  },
  'user:read': {
    resource: 'user',
    action: 'read',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.user.read',
  },
  'user:invite': {
    resource: 'user',
    action: 'invite',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.user.invite',
  },
  'user:update': {
    resource: 'user',
    action: 'update',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.user.update',
  },
  'user:suspend': {
    resource: 'user',
    action: 'suspend',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.user.suspend',
  },
  'user:reactivate': {
    resource: 'user',
    action: 'reactivate',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.user.reactivate',
  },
  'user:delete': {
    resource: 'user',
    action: 'delete',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.user.delete',
  },
  'user:reset_password': {
    resource: 'user',
    action: 'reset_password',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.user.reset_password',
  },
  'user:reset_mfa': {
    resource: 'user',
    action: 'reset_mfa',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.user.reset_mfa',
  },
  'user:force_logout': {
    resource: 'user',
    action: 'force_logout',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.user.force_logout',
  },
  'user:read_sessions': {
    resource: 'user',
    action: 'read_sessions',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.user.read_sessions',
  },
  'user:impersonate': {
    resource: 'user',
    action: 'impersonate',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.user.impersonate',
  },
  'invitation:read': {
    resource: 'invitation',
    action: 'read',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invitation.read',
  },
  'invitation:create': {
    resource: 'invitation',
    action: 'create',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invitation.create',
  },
  'invitation:resend': {
    resource: 'invitation',
    action: 'resend',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invitation.resend',
  },
  'invitation:revoke': {
    resource: 'invitation',
    action: 'revoke',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invitation.revoke',
  },
  'employee:read': {
    resource: 'employee',
    action: 'read',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.employee.read',
  },
  'employee:update': {
    resource: 'employee',
    action: 'update',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.employee.update',
  },
  'employee:view_org_chart': {
    resource: 'employee',
    action: 'view_org_chart',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.employee.view_org_chart',
  },
  'employee:view_capacity': {
    resource: 'employee',
    action: 'view_capacity',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.employee.view_capacity',
  },
  'employee:manage_employment': {
    resource: 'employee',
    action: 'manage_employment',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.employee.manage_employment',
  },
  'employee:view_personal_data': {
    resource: 'employee',
    action: 'view_personal_data',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.employee.view_personal_data',
  },
  'employee:view_cost_rate': {
    resource: 'employee',
    action: 'view_cost_rate',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.employee.view_cost_rate',
  },
  'employee:manage_cost_rate': {
    resource: 'employee',
    action: 'manage_cost_rate',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.employee.manage_cost_rate',
  },
  'employee:view_drilldown': {
    resource: 'employee',
    action: 'view_drilldown',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.employee.view_drilldown',
  },
  'role:read': {
    resource: 'role',
    action: 'read',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.role.read',
  },
  'role:create': {
    resource: 'role',
    action: 'create',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.role.create',
  },
  'role:update': {
    resource: 'role',
    action: 'update',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.role.update',
  },
  'role:delete': {
    resource: 'role',
    action: 'delete',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.role.delete',
  },
  'role:assign': {
    resource: 'role',
    action: 'assign',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.role.assign',
  },
  'role:revoke': {
    resource: 'role',
    action: 'revoke',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.role.revoke',
  },
  'permission:read': {
    resource: 'permission',
    action: 'read',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.permission.read',
  },
  'permission:override_read': {
    resource: 'permission',
    action: 'override_read',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.permission.override_read',
  },
  'permission:override': {
    resource: 'permission',
    action: 'override',
    domain: 'iam',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.permission.override',
  },
  'permission:explain': {
    resource: 'permission',
    action: 'explain',
    domain: 'iam',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.permission.explain',
  },
  'acl:read': {
    resource: 'acl',
    action: 'read',
    domain: 'iam',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.acl.read',
  },
  'acl:grant': {
    resource: 'acl',
    action: 'grant',
    domain: 'iam',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.acl.grant',
  },
  'acl:revoke': {
    resource: 'acl',
    action: 'revoke',
    domain: 'iam',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.acl.revoke',
  },
  'project:read': {
    resource: 'project',
    action: 'read',
    domain: 'project',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.project.read',
  },
  'project:create': {
    resource: 'project',
    action: 'create',
    domain: 'project',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.project.create',
  },
  'project:update': {
    resource: 'project',
    action: 'update',
    domain: 'project',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.project.update',
  },
  'project:archive': {
    resource: 'project',
    action: 'archive',
    domain: 'project',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.project.archive',
  },
  'project:delete': {
    resource: 'project',
    action: 'delete',
    domain: 'project',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.project.delete',
  },
  'project:manage_members': {
    resource: 'project',
    action: 'manage_members',
    domain: 'project',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.project.manage_members',
  },
  'project:manage_settings': {
    resource: 'project',
    action: 'manage_settings',
    domain: 'project',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.project.manage_settings',
  },
  'project:manage_visibility': {
    resource: 'project',
    action: 'manage_visibility',
    domain: 'project',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.project.manage_visibility',
  },
  'project:manage_labels': {
    resource: 'project',
    action: 'manage_labels',
    domain: 'project',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.project.manage_labels',
  },
  'project:view_budget': {
    resource: 'project',
    action: 'view_budget',
    domain: 'project',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.project.view_budget',
  },
  'project:manage_budget': {
    resource: 'project',
    action: 'manage_budget',
    domain: 'project',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.project.manage_budget',
  },
  'project:view_financials': {
    resource: 'project',
    action: 'view_financials',
    domain: 'project',
    requiredLevel: 'VIEWER',
    dangerous: true,
    descriptionKey: 'permission.project.view_financials',
  },
  'board:read': {
    resource: 'board',
    action: 'read',
    domain: 'task',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.board.read',
  },
  'board:create': {
    resource: 'board',
    action: 'create',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.board.create',
  },
  'board:update': {
    resource: 'board',
    action: 'update',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.board.update',
  },
  'board:delete': {
    resource: 'board',
    action: 'delete',
    domain: 'task',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.board.delete',
  },
  'board:manage_columns': {
    resource: 'board',
    action: 'manage_columns',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.board.manage_columns',
  },
  'board:override_wip_limit': {
    resource: 'board',
    action: 'override_wip_limit',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.board.override_wip_limit',
  },
  'task:read': {
    resource: 'task',
    action: 'read',
    domain: 'task',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.task.read',
  },
  'task:create': {
    resource: 'task',
    action: 'create',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.create',
  },
  'task:update': {
    resource: 'task',
    action: 'update',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.update',
  },
  'task:move': {
    resource: 'task',
    action: 'move',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.move',
  },
  'task:assign': {
    resource: 'task',
    action: 'assign',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.assign',
  },
  'task:estimate': {
    resource: 'task',
    action: 'estimate',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.estimate',
  },
  'task:link': {
    resource: 'task',
    action: 'link',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.link',
  },
  'task:manage_labels': {
    resource: 'task',
    action: 'manage_labels',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.manage_labels',
  },
  'task:manage_sprint': {
    resource: 'task',
    action: 'manage_sprint',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.manage_sprint',
  },
  'task:watch': {
    resource: 'task',
    action: 'watch',
    domain: 'task',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.task.watch',
  },
  'task:delete': {
    resource: 'task',
    action: 'delete',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.delete',
  },
  'task:restore': {
    resource: 'task',
    action: 'restore',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.task.restore',
  },
  'task:bulk_edit': {
    resource: 'task',
    action: 'bulk_edit',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.task.bulk_edit',
  },
  'task:export': {
    resource: 'task',
    action: 'export',
    domain: 'task',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.task.export',
  },
  'sprint:read': {
    resource: 'sprint',
    action: 'read',
    domain: 'task',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.sprint.read',
  },
  'sprint:create': {
    resource: 'sprint',
    action: 'create',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.sprint.create',
  },
  'sprint:update': {
    resource: 'sprint',
    action: 'update',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.sprint.update',
  },
  'sprint:start': {
    resource: 'sprint',
    action: 'start',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.sprint.start',
  },
  'sprint:complete': {
    resource: 'sprint',
    action: 'complete',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.sprint.complete',
  },
  'sprint:delete': {
    resource: 'sprint',
    action: 'delete',
    domain: 'task',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.sprint.delete',
  },
  'comment:read': {
    resource: 'comment',
    action: 'read',
    domain: 'task',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.comment.read',
  },
  'comment:create': {
    resource: 'comment',
    action: 'create',
    domain: 'task',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.comment.create',
  },
  'comment:update_own': {
    resource: 'comment',
    action: 'update_own',
    domain: 'task',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.comment.update_own',
  },
  'comment:update_any': {
    resource: 'comment',
    action: 'update_any',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.comment.update_any',
  },
  'comment:delete_own': {
    resource: 'comment',
    action: 'delete_own',
    domain: 'task',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.comment.delete_own',
  },
  'comment:delete_any': {
    resource: 'comment',
    action: 'delete_any',
    domain: 'task',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.comment.delete_any',
  },
  'comment:resolve': {
    resource: 'comment',
    action: 'resolve',
    domain: 'task',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.comment.resolve',
  },
  'doc:read': {
    resource: 'doc',
    action: 'read',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.doc.read',
  },
  'doc:create': {
    resource: 'doc',
    action: 'create',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.create',
  },
  'doc:update': {
    resource: 'doc',
    action: 'update',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.update',
  },
  'doc:move': {
    resource: 'doc',
    action: 'move',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.move',
  },
  'doc:delete': {
    resource: 'doc',
    action: 'delete',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.delete',
  },
  'doc:publish': {
    resource: 'doc',
    action: 'publish',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.publish',
  },
  'doc:view_history': {
    resource: 'doc',
    action: 'view_history',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.doc.view_history',
  },
  'doc:restore_version': {
    resource: 'doc',
    action: 'restore_version',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.restore_version',
  },
  'doc:export': {
    resource: 'doc',
    action: 'export',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.doc.export',
  },
  'doc:import': {
    resource: 'doc',
    action: 'import',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.doc.import',
  },
  'doc:share': {
    resource: 'doc',
    action: 'share',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.doc.share',
  },
  'doc:manage_acl': {
    resource: 'doc',
    action: 'manage_acl',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.doc.manage_acl',
  },
  'kb_space:read': {
    resource: 'kb_space',
    action: 'read',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.kb_space.read',
  },
  'kb_space:create': {
    resource: 'kb_space',
    action: 'create',
    domain: 'knowledge',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.kb_space.create',
  },
  'kb_space:update': {
    resource: 'kb_space',
    action: 'update',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.kb_space.update',
  },
  'kb_space:delete': {
    resource: 'kb_space',
    action: 'delete',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.kb_space.delete',
  },
  'kb_space:manage_acl': {
    resource: 'kb_space',
    action: 'manage_acl',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.kb_space.manage_acl',
  },
  'kb_space:sync_git': {
    resource: 'kb_space',
    action: 'sync_git',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.kb_space.sync_git',
  },
  'kb_space:import': {
    resource: 'kb_space',
    action: 'import',
    domain: 'knowledge',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.kb_space.import',
  },
  'kb_space:export': {
    resource: 'kb_space',
    action: 'export',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.kb_space.export',
  },
  'kb_note:read': {
    resource: 'kb_note',
    action: 'read',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.kb_note.read',
  },
  'kb_note:create': {
    resource: 'kb_note',
    action: 'create',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.kb_note.create',
  },
  'kb_note:update': {
    resource: 'kb_note',
    action: 'update',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.kb_note.update',
  },
  'kb_note:delete': {
    resource: 'kb_note',
    action: 'delete',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.kb_note.delete',
  },
  'kb_note:manage_tags': {
    resource: 'kb_note',
    action: 'manage_tags',
    domain: 'knowledge',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.kb_note.manage_tags',
  },
  'kb_note:view_graph': {
    resource: 'kb_note',
    action: 'view_graph',
    domain: 'knowledge',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.kb_note.view_graph',
  },
  'file:read': {
    resource: 'file',
    action: 'read',
    domain: 'file',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.file.read',
  },
  'file:download': {
    resource: 'file',
    action: 'download',
    domain: 'file',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.file.download',
  },
  'file:upload': {
    resource: 'file',
    action: 'upload',
    domain: 'file',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.file.upload',
  },
  'file:update': {
    resource: 'file',
    action: 'update',
    domain: 'file',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.file.update',
  },
  'file:delete': {
    resource: 'file',
    action: 'delete',
    domain: 'file',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.file.delete',
  },
  'file:restore': {
    resource: 'file',
    action: 'restore',
    domain: 'file',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.file.restore',
  },
  'file:manage_versions': {
    resource: 'file',
    action: 'manage_versions',
    domain: 'file',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.file.manage_versions',
  },
  'file:manage_folders': {
    resource: 'file',
    action: 'manage_folders',
    domain: 'file',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.file.manage_folders',
  },
  'file:manage_acl': {
    resource: 'file',
    action: 'manage_acl',
    domain: 'file',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.file.manage_acl',
  },
  'file:view_quarantined': {
    resource: 'file',
    action: 'view_quarantined',
    domain: 'file',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.file.view_quarantined',
  },
  'file:download_quarantined': {
    resource: 'file',
    action: 'download_quarantined',
    domain: 'file',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.file.download_quarantined',
  },
  'file:manage_retention': {
    resource: 'file',
    action: 'manage_retention',
    domain: 'file',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.file.manage_retention',
  },
  'file:view_quota': {
    resource: 'file',
    action: 'view_quota',
    domain: 'file',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.file.view_quota',
  },
  'vault:read': {
    resource: 'vault',
    action: 'read',
    domain: 'vault',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.vault.read',
  },
  'vault:create': {
    resource: 'vault',
    action: 'create',
    domain: 'vault',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.vault.create',
  },
  'vault:update': {
    resource: 'vault',
    action: 'update',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.vault.update',
  },
  'vault:delete': {
    resource: 'vault',
    action: 'delete',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.vault.delete',
  },
  'vault:view_members': {
    resource: 'vault',
    action: 'view_members',
    domain: 'vault',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.vault.view_members',
  },
  'vault:share': {
    resource: 'vault',
    action: 'share',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.vault.share',
  },
  'vault:revoke_access': {
    resource: 'vault',
    action: 'revoke_access',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.vault.revoke_access',
  },
  'vault:rotate_keys': {
    resource: 'vault',
    action: 'rotate_keys',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.vault.rotate_keys',
  },
  'vault:rotate_payload': {
    resource: 'vault',
    action: 'rotate_payload',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.vault.rotate_payload',
  },
  'vault:view_access_log': {
    resource: 'vault',
    action: 'view_access_log',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.vault.view_access_log',
  },
  'vault:manage_org_escrow': {
    resource: 'vault',
    action: 'manage_org_escrow',
    domain: 'vault',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.vault.manage_org_escrow',
  },
  'vault:use_org_escrow': {
    resource: 'vault',
    action: 'use_org_escrow',
    domain: 'vault',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.vault.use_org_escrow',
  },
  'vault_item:read': {
    resource: 'vault_item',
    action: 'read',
    domain: 'vault',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.vault_item.read',
  },
  'vault_item:create': {
    resource: 'vault_item',
    action: 'create',
    domain: 'vault',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.vault_item.create',
  },
  'vault_item:update': {
    resource: 'vault_item',
    action: 'update',
    domain: 'vault',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.vault_item.update',
  },
  'vault_item:delete': {
    resource: 'vault_item',
    action: 'delete',
    domain: 'vault',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.vault_item.delete',
  },
  'vault_item:decrypt': {
    resource: 'vault_item',
    action: 'decrypt',
    domain: 'vault',
    requiredLevel: 'VIEWER',
    dangerous: true,
    descriptionKey: 'permission.vault_item.decrypt',
  },
  'vault_item:export': {
    resource: 'vault_item',
    action: 'export',
    domain: 'vault',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.vault_item.export',
  },
  'vault_item:view_history': {
    resource: 'vault_item',
    action: 'view_history',
    domain: 'vault',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.vault_item.view_history',
  },
  'secure_link:read': {
    resource: 'secure_link',
    action: 'read',
    domain: 'secure-link',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.secure_link.read',
  },
  'secure_link:read_any': {
    resource: 'secure_link',
    action: 'read_any',
    domain: 'secure-link',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.secure_link.read_any',
  },
  'secure_link:create': {
    resource: 'secure_link',
    action: 'create',
    domain: 'secure-link',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.secure_link.create',
  },
  'secure_link:attach_resource': {
    resource: 'secure_link',
    action: 'attach_resource',
    domain: 'secure-link',
    requiredLevel: 'VIEWER',
    dangerous: true,
    descriptionKey: 'permission.secure_link.attach_resource',
  },
  'secure_link:revoke': {
    resource: 'secure_link',
    action: 'revoke',
    domain: 'secure-link',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.secure_link.revoke',
  },
  'secure_link:view_access_log': {
    resource: 'secure_link',
    action: 'view_access_log',
    domain: 'secure-link',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.secure_link.view_access_log',
  },
  'secure_link:manage_policy': {
    resource: 'secure_link',
    action: 'manage_policy',
    domain: 'secure-link',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.secure_link.manage_policy',
  },
  'time:track': {
    resource: 'time',
    action: 'track',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.track',
  },
  'time:manage_activities': {
    resource: 'time',
    action: 'manage_activities',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.manage_activities',
  },
  'time:reverse_entry': {
    resource: 'time',
    action: 'reverse_entry',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.time.reverse_entry',
  },
  'time:read_own': {
    resource: 'time',
    action: 'read_own',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.read_own',
  },
  'time:read_team': {
    resource: 'time',
    action: 'read_team',
    domain: 'time',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.time.read_team',
  },
  'time:read_all': {
    resource: 'time',
    action: 'read_all',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.time.read_all',
  },
  'time:create_own': {
    resource: 'time',
    action: 'create_own',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.create_own',
  },
  'time:update_own': {
    resource: 'time',
    action: 'update_own',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.update_own',
  },
  'time:delete_own': {
    resource: 'time',
    action: 'delete_own',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.delete_own',
  },
  'time:update_any': {
    resource: 'time',
    action: 'update_any',
    domain: 'time',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.time.update_any',
  },
  'time:delete_any': {
    resource: 'time',
    action: 'delete_any',
    domain: 'time',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.time.delete_any',
  },
  'time:override': {
    resource: 'time',
    action: 'override',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.time.override',
  },
  'time:manage_policy': {
    resource: 'time',
    action: 'manage_policy',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.time.manage_policy',
  },
  'time:view_cost': {
    resource: 'time',
    action: 'view_cost',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.time.view_cost',
  },
  'time:view_bill_rate': {
    resource: 'time',
    action: 'view_bill_rate',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.time.view_bill_rate',
  },
  'time:manage_bill_rate': {
    resource: 'time',
    action: 'manage_bill_rate',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.time.manage_bill_rate',
  },
  'time:export': {
    resource: 'time',
    action: 'export',
    domain: 'time',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.time.export',
  },
  'timesheet:read_own': {
    resource: 'timesheet',
    action: 'read_own',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.timesheet.read_own',
  },
  'timesheet:read_team': {
    resource: 'timesheet',
    action: 'read_team',
    domain: 'time',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.timesheet.read_team',
  },
  'timesheet:read_all': {
    resource: 'timesheet',
    action: 'read_all',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.timesheet.read_all',
  },
  'timesheet:submit': {
    resource: 'timesheet',
    action: 'submit',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.timesheet.submit',
  },
  'timesheet:approve': {
    resource: 'timesheet',
    action: 'approve',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.timesheet.approve',
  },
  'timesheet:reject': {
    resource: 'timesheet',
    action: 'reject',
    domain: 'time',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.timesheet.reject',
  },
  'timesheet:reopen': {
    resource: 'timesheet',
    action: 'reopen',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.timesheet.reopen',
  },
  'timesheet:unlock_period': {
    resource: 'timesheet',
    action: 'unlock_period',
    domain: 'time',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.timesheet.unlock_period',
  },
  'channel:read': {
    resource: 'channel',
    action: 'read',
    domain: 'communication',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.channel.read',
  },
  'channel:read_any': {
    resource: 'channel',
    action: 'read_any',
    domain: 'communication',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.channel.read_any',
  },
  'channel:create': {
    resource: 'channel',
    action: 'create',
    domain: 'communication',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.channel.create',
  },
  'channel:update': {
    resource: 'channel',
    action: 'update',
    domain: 'communication',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.channel.update',
  },
  'channel:join_public': {
    resource: 'channel',
    action: 'join_public',
    domain: 'communication',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.channel.join_public',
  },
  'channel:manage_members': {
    resource: 'channel',
    action: 'manage_members',
    domain: 'communication',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.channel.manage_members',
  },
  'channel:archive': {
    resource: 'channel',
    action: 'archive',
    domain: 'communication',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.channel.archive',
  },
  'channel:delete': {
    resource: 'channel',
    action: 'delete',
    domain: 'communication',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.channel.delete',
  },
  'channel:export': {
    resource: 'channel',
    action: 'export',
    domain: 'communication',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.channel.export',
  },
  'message:create': {
    resource: 'message',
    action: 'create',
    domain: 'communication',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.message.create',
  },
  'message:update_own': {
    resource: 'message',
    action: 'update_own',
    domain: 'communication',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.message.update_own',
  },
  'message:delete_own': {
    resource: 'message',
    action: 'delete_own',
    domain: 'communication',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.message.delete_own',
  },
  'message:delete_any': {
    resource: 'message',
    action: 'delete_any',
    domain: 'communication',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.message.delete_any',
  },
  'message:pin': {
    resource: 'message',
    action: 'pin',
    domain: 'communication',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.message.pin',
  },
  'message:mention_channel': {
    resource: 'message',
    action: 'mention_channel',
    domain: 'communication',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.message.mention_channel',
  },
  'message:react': {
    resource: 'message',
    action: 'react',
    domain: 'communication',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.message.react',
  },
  'message:search': {
    resource: 'message',
    action: 'search',
    domain: 'communication',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.message.search',
  },
  'dashboard:read': {
    resource: 'dashboard',
    action: 'read',
    domain: 'analytics',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.dashboard.read',
  },
  'dashboard:create': {
    resource: 'dashboard',
    action: 'create',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.dashboard.create',
  },
  'dashboard:update': {
    resource: 'dashboard',
    action: 'update',
    domain: 'analytics',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.dashboard.update',
  },
  'dashboard:delete': {
    resource: 'dashboard',
    action: 'delete',
    domain: 'analytics',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.dashboard.delete',
  },
  'dashboard:share': {
    resource: 'dashboard',
    action: 'share',
    domain: 'analytics',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.dashboard.share',
  },
  'report:read': {
    resource: 'report',
    action: 'read',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.report.read',
  },
  'report:read_team': {
    resource: 'report',
    action: 'read_team',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.report.read_team',
  },
  'report:read_org': {
    resource: 'report',
    action: 'read_org',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.report.read_org',
  },
  'report:read_people': {
    resource: 'report',
    action: 'read_people',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.report.read_people',
  },
  'report:view_cost': {
    resource: 'report',
    action: 'view_cost',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.report.view_cost',
  },
  'report:view_margin': {
    resource: 'report',
    action: 'view_margin',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.report.view_margin',
  },
  'report:export': {
    resource: 'report',
    action: 'export',
    domain: 'analytics',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.report.export',
  },
  'integration:read': {
    resource: 'integration',
    action: 'read',
    domain: 'integration',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.integration.read',
  },
  'integration:connect': {
    resource: 'integration',
    action: 'connect',
    domain: 'integration',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.integration.connect',
  },
  'integration:disconnect': {
    resource: 'integration',
    action: 'disconnect',
    domain: 'integration',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.integration.disconnect',
  },
  'integration:manage_secrets': {
    resource: 'integration',
    action: 'manage_secrets',
    domain: 'integration',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.integration.manage_secrets',
  },
  'repo_link:read': {
    resource: 'repo_link',
    action: 'read',
    domain: 'integration',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.repo_link.read',
  },
  'repo_link:create': {
    resource: 'repo_link',
    action: 'create',
    domain: 'integration',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.repo_link.create',
  },
  'repo_link:delete': {
    resource: 'repo_link',
    action: 'delete',
    domain: 'integration',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.repo_link.delete',
  },
  'ci:read': {
    resource: 'ci',
    action: 'read',
    domain: 'integration',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.ci.read',
  },
  'ci:rerun': {
    resource: 'ci',
    action: 'rerun',
    domain: 'integration',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.ci.rerun',
  },
  'ci:cancel': {
    resource: 'ci',
    action: 'cancel',
    domain: 'integration',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.ci.cancel',
  },
  'deployment:read': {
    resource: 'deployment',
    action: 'read',
    domain: 'integration',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.deployment.read',
  },
  'deployment:trigger': {
    resource: 'deployment',
    action: 'trigger',
    domain: 'integration',
    requiredLevel: 'EDITOR',
    dangerous: true,
    descriptionKey: 'permission.deployment.trigger',
  },
  'webhook:view_deliveries': {
    resource: 'webhook',
    action: 'view_deliveries',
    domain: 'integration',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.webhook.view_deliveries',
  },
  'webhook:replay': {
    resource: 'webhook',
    action: 'replay',
    domain: 'integration',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.webhook.replay',
  },
  'ai:use': {
    resource: 'ai',
    action: 'use',
    domain: 'ai',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.ai.use',
  },
  'ai:use_project_context': {
    resource: 'ai',
    action: 'use_project_context',
    domain: 'ai',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.ai.use_project_context',
  },
  'ai:read_own_threads': {
    resource: 'ai',
    action: 'read_own_threads',
    domain: 'ai',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.ai.read_own_threads',
  },
  'ai:read_any_thread': {
    resource: 'ai',
    action: 'read_any_thread',
    domain: 'ai',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.ai.read_any_thread',
  },
  'ai:delete_thread': {
    resource: 'ai',
    action: 'delete_thread',
    domain: 'ai',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.ai.delete_thread',
  },
  'ai:run_tools': {
    resource: 'ai',
    action: 'run_tools',
    domain: 'ai',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.ai.run_tools',
  },
  'ai:view_usage': {
    resource: 'ai',
    action: 'view_usage',
    domain: 'ai',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.ai.view_usage',
  },
  'ai:manage_budget': {
    resource: 'ai',
    action: 'manage_budget',
    domain: 'ai',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.ai.manage_budget',
  },
  'ai:manage_tool_policy': {
    resource: 'ai',
    action: 'manage_tool_policy',
    domain: 'ai',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.ai.manage_tool_policy',
  },
  'ai:configure_providers': {
    resource: 'ai',
    action: 'configure_providers',
    domain: 'ai',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.ai.configure_providers',
  },
  'ai:reindex_embeddings': {
    resource: 'ai',
    action: 'reindex_embeddings',
    domain: 'ai',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.ai.reindex_embeddings',
  },
  'delivery:access': {
    resource: 'delivery',
    action: 'access',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.delivery.access',
  },
  'client:read': {
    resource: 'client',
    action: 'read',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.client.read',
  },
  'client:create': {
    resource: 'client',
    action: 'create',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.client.create',
  },
  'client:update': {
    resource: 'client',
    action: 'update',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.client.update',
  },
  'client:delete': {
    resource: 'client',
    action: 'delete',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.client.delete',
  },
  'client:manage_contacts': {
    resource: 'client',
    action: 'manage_contacts',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.client.manage_contacts',
  },
  'contract:read': {
    resource: 'contract',
    action: 'read',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.contract.read',
  },
  'contract:create': {
    resource: 'contract',
    action: 'create',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.contract.create',
  },
  'contract:update': {
    resource: 'contract',
    action: 'update',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.contract.update',
  },
  'contract:change_status': {
    resource: 'contract',
    action: 'change_status',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.contract.change_status',
  },
  'contract:terminate': {
    resource: 'contract',
    action: 'terminate',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.contract.terminate',
  },
  'contract:view_rates': {
    resource: 'contract',
    action: 'view_rates',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.contract.view_rates',
  },
  'contract:manage_rates': {
    resource: 'contract',
    action: 'manage_rates',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.contract.manage_rates',
  },
  'contract:view_nda': {
    resource: 'contract',
    action: 'view_nda',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.contract.view_nda',
  },
  'invoice:read': {
    resource: 'invoice',
    action: 'read',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invoice.read',
  },
  'invoice:create': {
    resource: 'invoice',
    action: 'create',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invoice.create',
  },
  'invoice:update': {
    resource: 'invoice',
    action: 'update',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.invoice.update',
  },
  'invoice:issue': {
    resource: 'invoice',
    action: 'issue',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.invoice.issue',
  },
  'invoice:send': {
    resource: 'invoice',
    action: 'send',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.invoice.send',
  },
  'invoice:void': {
    resource: 'invoice',
    action: 'void',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.invoice.void',
  },
  'invoice:export': {
    resource: 'invoice',
    action: 'export',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.invoice.export',
  },
  'payment:read': {
    resource: 'payment',
    action: 'read',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.payment.read',
  },
  'payment:record': {
    resource: 'payment',
    action: 'record',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.payment.record',
  },
  'payment:delete': {
    resource: 'payment',
    action: 'delete',
    domain: 'delivery',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.payment.delete',
  },
  'milestone:read': {
    resource: 'milestone',
    action: 'read',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.milestone.read',
  },
  'milestone:create': {
    resource: 'milestone',
    action: 'create',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.milestone.create',
  },
  'milestone:update': {
    resource: 'milestone',
    action: 'update',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.milestone.update',
  },
  'milestone:accept': {
    resource: 'milestone',
    action: 'accept',
    domain: 'delivery',
    requiredLevel: 'MANAGER',
    dangerous: true,
    descriptionKey: 'permission.milestone.accept',
  },
  'call:read': {
    resource: 'call',
    action: 'read',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.call.read',
  },
  'call:create': {
    resource: 'call',
    action: 'create',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.call.create',
  },
  'call:update': {
    resource: 'call',
    action: 'update',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.call.update',
  },
  'call:delete': {
    resource: 'call',
    action: 'delete',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.call.delete',
  },
  'call:manage_participants': {
    resource: 'call',
    action: 'manage_participants',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.call.manage_participants',
  },
  'call:view_recording': {
    resource: 'call',
    action: 'view_recording',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: true,
    descriptionKey: 'permission.call.view_recording',
  },
  'call:manage_summary': {
    resource: 'call',
    action: 'manage_summary',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.call.manage_summary',
  },
  'call:export': {
    resource: 'call',
    action: 'export',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.call.export',
  },
  'action_item:read': {
    resource: 'action_item',
    action: 'read',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.action_item.read',
  },
  'action_item:create': {
    resource: 'action_item',
    action: 'create',
    domain: 'delivery',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.action_item.create',
  },
  'action_item:update': {
    resource: 'action_item',
    action: 'update',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.action_item.update',
  },
  'action_item:complete': {
    resource: 'action_item',
    action: 'complete',
    domain: 'delivery',
    requiredLevel: 'COMMENTER',
    dangerous: false,
    descriptionKey: 'permission.action_item.complete',
  },
  'risk:read': {
    resource: 'risk',
    action: 'read',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.risk.read',
  },
  'risk:create': {
    resource: 'risk',
    action: 'create',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.risk.create',
  },
  'risk:update': {
    resource: 'risk',
    action: 'update',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.risk.update',
  },
  'risk:close': {
    resource: 'risk',
    action: 'close',
    domain: 'delivery',
    requiredLevel: 'MANAGER',
    dangerous: false,
    descriptionKey: 'permission.risk.close',
  },
  'stakeholder:read': {
    resource: 'stakeholder',
    action: 'read',
    domain: 'delivery',
    requiredLevel: 'VIEWER',
    dangerous: false,
    descriptionKey: 'permission.stakeholder.read',
  },
  'stakeholder:manage': {
    resource: 'stakeholder',
    action: 'manage',
    domain: 'delivery',
    requiredLevel: 'EDITOR',
    dangerous: false,
    descriptionKey: 'permission.stakeholder.manage',
  },
  'audit:read': {
    resource: 'audit',
    action: 'read',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.audit.read',
  },
  'audit:read_security': {
    resource: 'audit',
    action: 'read_security',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.audit.read_security',
  },
  'audit:export': {
    resource: 'audit',
    action: 'export',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.audit.export',
  },
  'audit:manage_retention': {
    resource: 'audit',
    action: 'manage_retention',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.audit.manage_retention',
  },
  'settings:read': {
    resource: 'settings',
    action: 'read',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.settings.read',
  },
  'settings:update': {
    resource: 'settings',
    action: 'update',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.settings.update',
  },
  'settings:manage_email': {
    resource: 'settings',
    action: 'manage_email',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.settings.manage_email',
  },
  'settings:manage_storage_backend': {
    resource: 'settings',
    action: 'manage_storage_backend',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.settings.manage_storage_backend',
  },
  'settings:manage_backup': {
    resource: 'settings',
    action: 'manage_backup',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.settings.manage_backup',
  },
  'settings:run_backup': {
    resource: 'settings',
    action: 'run_backup',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.settings.run_backup',
  },
  'settings:restore_backup': {
    resource: 'settings',
    action: 'restore_backup',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.settings.restore_backup',
  },
  'settings:view_system_health': {
    resource: 'settings',
    action: 'view_system_health',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.settings.view_system_health',
  },
  'settings:manage_feature_flags': {
    resource: 'settings',
    action: 'manage_feature_flags',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.settings.manage_feature_flags',
  },
  'api_token:read_own': {
    resource: 'api_token',
    action: 'read_own',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.api_token.read_own',
  },
  'api_token:create_own': {
    resource: 'api_token',
    action: 'create_own',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.api_token.create_own',
  },
  'api_token:revoke_own': {
    resource: 'api_token',
    action: 'revoke_own',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.api_token.revoke_own',
  },
  'api_token:read_any': {
    resource: 'api_token',
    action: 'read_any',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.api_token.read_any',
  },
  'api_token:revoke_any': {
    resource: 'api_token',
    action: 'revoke_any',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.api_token.revoke_any',
  },
  'mcp:connect': {
    resource: 'mcp',
    action: 'connect',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.mcp.connect',
  },
  'mcp:use_write_tools': {
    resource: 'mcp',
    action: 'use_write_tools',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.mcp.use_write_tools',
  },
  'mcp:manage_clients': {
    resource: 'mcp',
    action: 'manage_clients',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mcp.manage_clients',
  },
  'mcp:manage_tool_policy': {
    resource: 'mcp',
    action: 'manage_tool_policy',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mcp.manage_tool_policy',
  },
  'mcp:read_any_session': {
    resource: 'mcp',
    action: 'read_any_session',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mcp.read_any_session',
  },
  'mcp:revoke_any_session': {
    resource: 'mcp',
    action: 'revoke_any_session',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.mcp.revoke_any_session',
  },
  'notification:read_own': {
    resource: 'notification',
    action: 'read_own',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.notification.read_own',
  },
  'notification:manage_preferences_own': {
    resource: 'notification',
    action: 'manage_preferences_own',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.notification.manage_preferences_own',
  },
  'notification:manage_templates': {
    resource: 'notification',
    action: 'manage_templates',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.notification.manage_templates',
  },
  'onboarding:read': {
    resource: 'onboarding',
    action: 'read',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.onboarding.read',
  },
  'onboarding:manage': {
    resource: 'onboarding',
    action: 'manage',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.onboarding.manage',
  },
  'material:read': {
    resource: 'material',
    action: 'read',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.material.read',
  },
  'material:create': {
    resource: 'material',
    action: 'create',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.material.create',
  },
  'material:update': {
    resource: 'material',
    action: 'update',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.material.update',
  },
  'material:delete': {
    resource: 'material',
    action: 'delete',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.material.delete',
  },
  'search:reindex': {
    resource: 'search',
    action: 'reindex',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.search.reindex',
  },
  'job:read': {
    resource: 'job',
    action: 'read',
    domain: 'platform',
    requiredLevel: null,
    dangerous: false,
    descriptionKey: 'permission.job.read',
  },
  'job:retry': {
    resource: 'job',
    action: 'retry',
    domain: 'platform',
    requiredLevel: null,
    dangerous: true,
    descriptionKey: 'permission.job.retry',
  },
};

export const PERMISSION_SET: ReadonlySet<string> = new Set<string>(PERMISSIONS);

export const isPermissionKey = (value: string): value is PermissionKey => PERMISSION_SET.has(value);

/** `null` means the key carries no resource context; `undefined` is not a possible answer. */
export const requiredLevel = (key: PermissionKey): AccessLevel | null =>
  PERMISSION_META[key].requiredLevel;
