import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';
import { describe, expect, it } from 'vitest';

import type { paths } from '../../src/shared/api/schemas/api-schema.js';

const SPEC_URL = new URL('../../../../docs/api/openapi.yaml', import.meta.url);
const GENERATED_PATH = fileURLToPath(
  new URL('../../src/shared/api/schemas/api-schema.d.ts', import.meta.url),
);

const committed = (): string => readFileSync(GENERATED_PATH, 'utf8');

/**
 * The committed types are what the current specification generates — checked here as well as in
 * CI, because a check only CI knows how to run is a check nobody runs before pushing.
 *
 * The comparison starts at the first declaration: the CLI prepends a "do not edit" banner that the
 * programmatic API does not emit, and asserting on the banner would make this test about the
 * generator's preamble rather than about the types.
 */
describe('the generated client types are in step with the contract', () => {
  it('matches what openapi-typescript produces from docs/api/openapi.yaml today', async () => {
    const generated = astToString(await openapiTS(SPEC_URL));
    const file = committed();
    const start = file.indexOf('export interface paths');

    expect(start, 'the generated file no longer starts with a `paths` declaration').toBeGreaterThan(
      0,
    );
    expect(
      file.slice(start),
      'run `pnpm api:gen` and commit the result — the specification moved without the types',
    ).toBe(generated);
  });

  it('keeps the banner that tells a reader not to edit it by hand', () => {
    expect(committed()).toContain('auto-generated by openapi-typescript');
  });
});

/**
 * The point of generating types at all: a wrong path, a wrong method or an undeclared parameter has
 * to be a compile error, not a 404 in production. These assertions are enforced by
 * `tsc -p tsconfig.test.json` (part of `pnpm typecheck`), not by the runner — a `@ts-expect-error`
 * that stops erroring fails the build on its own.
 */
describe('the contract is enforced by the compiler', () => {
  it('types the response of a declared operation', () => {
    const meta: paths['/meta']['get']['responses']['200']['content']['application/json'] = {
      apiVersion: 'v1',
      serverTime: '2026-07-27T09:41:12.004Z',
    };

    expect(meta.apiVersion).toBe('v1');
  });

  it('rejects a path the contract does not publish', () => {
    // @ts-expect-error `/tasks` is not an operation of this API
    type Missing = paths['/tasks'];

    expect<Missing | undefined>(undefined).toBeUndefined();
  });

  /**
   * `openapi-typescript` lists every HTTP method on every path and types the unpublished ones as
   * `never`, so the *key* exists and only a value for it is impossible. The assertion is therefore
   * written as an assignment: that is also the shape `openapi-fetch` checks when a call site picks
   * a method.
   */
  it('rejects a method the contract does not publish for a path', () => {
    // @ts-expect-error `/meta` publishes `get` only, so `post` is typed `never`
    const unsupported: NonNullable<paths['/meta']['post']> = {};

    expect(unsupported).toBeDefined();
  });

  it('rejects a query parameter the operation never declared', () => {
    // @ts-expect-error the operation declares no query parameters at all
    const query: NonNullable<paths['/meta']['get']['parameters']['query']> = { page: 1 };

    expect(query).toBeDefined();
  });
});
