/**
 * The tenant root, loaded and saved as a whole.
 *
 * Note what is *not* here: no method takes an `organizationId`. The tenant is the scope the caller
 * opened through `UnitOfWorkPort`, and a parameter beside it would be a second answer to the same
 * question — one the policy silently overrules, turning a mismatch into an empty result rather than
 * into an error (rules/tenancy-rls.mdc, 9; docs/security/rls-design.md).
 */

/** What an installation owner supplies when the first organization is created. */
export interface OrganizationDraft {
  readonly name: string;
  /** Globally unique; the only field of this table that is not scoped to a tenant. */
  readonly slug: string;
  readonly timezone: string;
  /** ISO 4217, three letters. */
  readonly defaultCurrency: string;
}

/** The read model of the tenant root; deliberately not the Prisma row. */
export interface OrganizationSummary {
  readonly id: string;
  readonly slug: string;
  readonly name: string;
  readonly timezone: string;
  readonly defaultCurrency: string;
}

/** Who the organization belongs to, written in the same statement as the organization itself. */
export interface OrganizationOwnerDraft {
  readonly email: string;
  /** Already hashed by `PasswordHasherPort`; a plaintext password never crosses this boundary. */
  readonly passwordHash: string;
  readonly locale: string;
  readonly timezone: string;
}

/** The two rows a new installation cannot exist without, and the ids they were given. */
export interface BootstrappedOrganization {
  readonly organizationId: string;
  readonly ownerId: string;
}

export interface OrganizationRepositoryPort {
  /**
   * Inserts the tenant root **and its owner**, as the organization of the current scope, in one
   * statement.
   *
   * One statement because the two rows reference each other: `organizations.owner_id` is NOT NULL and
   * points at `users`, while `users.organization_id` points back. Written as two statements, whichever
   * goes first violates a constraint — which is why the column used to be nullable and filled in
   * afterwards. A single data-modifying `WITH` avoids that without weakening anything: foreign keys
   * are `AFTER ROW` triggers that fire when the statement ends, and by then both rows exist. The
   * alternative, `DEFERRABLE INITIALLY DEFERRED`, would buy the same insert order by giving *every*
   * transaction the right to point at a row that does not exist (docs/architecture/data-model.md,
   * «Про `Organization.ownerId`»).
   *
   * There is no `id` in either draft, and that is the mechanism rather than a convenience: the
   * organization's primary key *is* the tenant, its policy compares `id` against
   * `app.organization_id`, and any other value would be refused by `WITH CHECK`. Taking it from the
   * scope makes the refusal impossible to reach — and makes it impossible to create an organization
   * other than the one the caller declared it was acting as (docs/security/rls-design.md, «Особый
   * случай: organizations»). The owner's id is generated by the adapter for the same statement.
   */
  createWithOwner(
    draft: OrganizationDraft,
    owner: OrganizationOwnerDraft,
  ): Promise<BootstrappedOrganization>;

  /** The organization of the current scope, or `null` when it does not exist or is soft-deleted. */
  findCurrent(): Promise<OrganizationSummary | null>;
}
