/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version and clock of this API.
         * @description Read before a session exists: the client checks that it understands the API version it is
         *     talking to, and reconciles clock skew for anything it renders as a relative time.
         *
         *     The operation takes no parameters and rejects the ones it was not given — an endpoint that
         *     silently ignores an unknown query parameter is how a typo reaches production as a 200.
         */
        get: operations["getApiMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiMeta: {
            /**
             * @description The version segment this response was served under.
             * @example v1
             */
            apiVersion: string;
            /**
             * Format: date-time
             * @description The server's clock at the moment of the response, in UTC.
             * @example 2026-07-27T09:41:12.004Z
             */
            serverTime: string;
        };
        /**
         * @description The closed catalog of machine-readable error codes. It is the same list as
         *     `packages/shared/src/errors/error-code.enums.ts`, and
         *     `packages/server/test/contract/error-codes.test.ts` fails the build if the two differ.
         *
         *     The client selects an i18n message by this value, so a code is never renamed and never
         *     reused with a different meaning.
         * @enum {string}
         */
        ErrorCode: "validation_failed" | "unauthenticated" | "route_not_found" | "payload_too_large" | "vault_locked" | "stale_version" | "idempotency_key_reuse" | "rate_limited" | "feature_disabled" | "service_unavailable" | "internal_error" | "organization_not_found" | "organization_forbidden" | "organization_already_exists" | "team_not_found" | "team_forbidden" | "team_already_exists" | "user_not_found" | "user_forbidden" | "user_already_exists" | "role_not_found" | "role_forbidden" | "role_already_exists" | "invitation_not_found" | "invitation_forbidden" | "invitation_already_exists" | "project_not_found" | "project_forbidden" | "project_already_exists" | "board_not_found" | "board_forbidden" | "board_already_exists" | "task_not_found" | "task_forbidden" | "task_already_exists" | "sprint_not_found" | "sprint_forbidden" | "sprint_already_exists" | "comment_not_found" | "comment_forbidden" | "comment_already_exists" | "doc_not_found" | "doc_forbidden" | "doc_already_exists" | "kb_note_not_found" | "kb_note_forbidden" | "kb_note_already_exists" | "file_not_found" | "file_forbidden" | "file_already_exists" | "vault_item_not_found" | "vault_item_forbidden" | "vault_item_already_exists" | "secure_link_not_found" | "secure_link_forbidden" | "secure_link_already_exists" | "time_entry_not_found" | "time_entry_forbidden" | "time_entry_already_exists" | "channel_not_found" | "channel_forbidden" | "channel_already_exists" | "message_not_found" | "message_forbidden" | "message_already_exists" | "dashboard_not_found" | "dashboard_forbidden" | "dashboard_already_exists";
        /**
         * @description Why one field was rejected. The list mirrors
         *     `packages/shared/src/errors/validation-issue.enums.ts`; anything a validator produces
         *     outside it is reported as `custom`, so this enum is exhaustive by construction.
         * @enum {string}
         */
        ValidationIssueCode: "invalid_type" | "too_big" | "too_small" | "invalid_format" | "not_multiple_of" | "unrecognized_keys" | "invalid_union" | "invalid_key" | "invalid_element" | "invalid_value" | "custom";
        ValidationIssue: {
            /**
             * @description The rejected field in dot notation over the request value — `title`,
             *     `amount.value`, `items[0].title`. An empty string means the value as a whole was
             *     wrong (a body that is not an object at all).
             * @example amount.value
             */
            path: string;
            code: components["schemas"]["ValidationIssueCode"];
            /**
             * @description English, for the developer reading a log. Never shown to a user.
             * @example Invalid input: expected number, received string
             */
            message: string;
        };
        /**
         * @description RFC 9457 problem document — the only error shape this API produces, validation included.
         *
         *     `instance` is deliberately absent. The field is optional in the RFC and the only honest
         *     value would be the request URL, which this product cannot print: it has routes whose path
         *     segment *is* the credential (`/l/{token}`), and a problem document is exactly the thing a
         *     user pastes into a support ticket. The occurrence is identified by `requestId`, which
         *     correlates to the log line without exposing anything.
         */
        Problem: {
            /**
             * Format: uri
             * @description Identifies the problem class. Not dereferenced at runtime.
             * @example https://bad-crm.dev/problems/validation-failed
             */
            type: string;
            /**
             * @description Short human-readable summary, for developers. May be reworded; do not parse.
             * @example Validation failed
             */
            title: string;
            /**
             * @description The HTTP status code, repeated in the body for logs and proxies.
             * @example 422
             */
            status: number;
            code: components["schemas"]["ErrorCode"];
            /**
             * @description Explanation of this occurrence, for the developer. **Absent on every 5xx**: the message
             *     of an unexpected exception is a driver sentence or a schema name, and each one hands an
             *     attacker a piece of the internals.
             * @example 2 fields are invalid
             */
            detail?: string;
            /**
             * @description Correlates this response with the server log. Also returned as `x-request-id`.
             * @example 01J8Z2F5Q3K9V6N0R4T7YB3XQD
             */
            requestId: string;
            /** @description Present on `validation_failed` only — one entry per rejected field. */
            errors?: components["schemas"]["ValidationIssue"][];
        };
        /**
         * @description The envelope of a table-shaped list (tasks, projects, employees, documents, invoices).
         *     Feeds — activity, comments, messages, notifications, audit — use the cursor parameters
         *     instead, because an offset over an append-heavy stream both duplicates and drops rows
         *     (`rules/api-contract.mdc`, §8).
         */
        OffsetPage: {
            /** @description Rows matching the same predicate as `items`, before pagination. */
            total: number;
            page: number;
            perPage: number;
        };
        /** @description The envelope of a feed. `nextCursor` is absent on the last page. */
        CursorPage: {
            /**
             * @description Opaque base64url of `{ sortKey, id }`. The `id` tie-breaker is mandatory: without it
             *     rows sharing a timestamp are skipped at the page boundary.
             */
            nextCursor: string | null;
        };
    };
    responses: {
        /** @description The request did not pass validation; `errors[]` names every field. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No credentials, or the access token expired. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Authenticated, and not allowed to do this **inside their own organization**. A resource
         *     belonging to another organization is answered 404, never 403 — otherwise the API tells an
         *     attacker which ids exist in tenants they cannot see (CLAUDE.md, invariant 2).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist, or exists in another organization. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Version conflict, duplicate key, or a replayed `Idempotency-Key`. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many requests. `Retry-After` says when to come back. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected failure. Carries no `detail`; quote `requestId` in a bug report. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description 1-based page number of an offset-paginated list. */
        Page: number;
        /** @description Page size of an offset-paginated list. Bounded, so one caller cannot ask for the table. */
        PerPage: number;
        /** @description Opaque cursor returned as `nextCursor` by the previous page. Absent on the first. */
        Cursor: string;
        /** @description Page size of a cursor-paginated feed. */
        Limit: number;
        /**
         * @description Client-generated key, mandatory on every unsafe operation that creates an entity, sends
         *     mail or spends money or tokens. A replay carrying the same request hash returns the stored
         *     response; the same key with a different hash is refused with 409 `idempotency_key_reuse`.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API described itself. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiMeta"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
